---
name: Git Mirror
# Mirror git repo to other sites

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Sync repo codeberg"
        uses: yesolutions/mirror-action@662fce0eced8996f64d7fa264d76cddd84827f33
        with:
          REMOTE: ${{ secrets.CODEBERG_URL }}
          GIT_USERNAME: ${{ secrets.CODEBERG_USER }}
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}

      - name: "Sync repo gitlab"
        uses: yesolutions/mirror-action@662fce0eced8996f64d7fa264d76cddd84827f33
        with:
          REMOTE: ${{ secrets.GITLAB_URL }}
          REMOTE_NAME: gitlab
          GIT_USERNAME: ${{ secrets.GITLAB_USER }}
          GIT_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
